# Generated by Django 5.0.3 on 2024-04-22 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_product_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('القاهرة', 'القاهرة'), ('الإسكندرية', 'الإسكندرية'), ('الجيزة', 'الجيزة'), ('الشرقية', 'الشرقية'), ('الدقهلية', 'الدقهلية'), ('القليوبية', 'القليوبية'), ('كفر الشيخ', 'كفر الشيخ'), ('الغربية', 'الغربية'), ('المنوفية', 'المنوفية'), ('دمياط', 'دمياط'), ('البحيرة', 'البحيرة'), ('الفيوم', 'الفيوم'), ('المنيا', 'المنيا'), ('أسيوط', 'أسيوط'), ('سوهاج', 'سوهاج'), ('قنا', 'قنا'), ('أسوان', 'أسوان'), ('الأقصر', 'الأقصر'), ('البحر الأحمر', 'البحر الأحمر'), ('مطروح', 'مطروح'), ('الوادي الجديد', 'الوادي الجديد'), ('شمال سيناء', 'شمال سيناء'), ('جنوب سيناء', 'جنوب سيناء')], max_length=50, verbose_name='المحافطة')),
                ('fee', models.PositiveIntegerField(verbose_name='مصاريف الشحن')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='الاسم الأخير')),
                ('city', models.CharField(choices=[('القاهرة', 'القاهرة'), ('الإسكندرية', 'الإسكندرية'), ('الجيزة', 'الجيزة'), ('الشرقية', 'الشرقية'), ('الدقهلية', 'الدقهلية'), ('القليوبية', 'القليوبية'), ('كفر الشيخ', 'كفر الشيخ'), ('الغربية', 'الغربية'), ('المنوفية', 'المنوفية'), ('دمياط', 'دمياط'), ('البحيرة', 'البحيرة'), ('الفيوم', 'الفيوم'), ('المنيا', 'المنيا'), ('أسيوط', 'أسيوط'), ('سوهاج', 'سوهاج'), ('قنا', 'قنا'), ('أسوان', 'أسوان'), ('الأقصر', 'الأقصر'), ('البحر الأحمر', 'البحر الأحمر'), ('مطروح', 'مطروح'), ('الوادي الجديد', 'الوادي الجديد'), ('شمال سيناء', 'شمال سيناء'), ('جنوب سيناء', 'جنوب سيناء')], max_length=50, verbose_name='المحافظة')),
                ('district', models.CharField(max_length=50, verbose_name='المنطقة')),
                ('street_address', models.CharField(max_length=150, verbose_name='عنوان الشارع')),
                ('house_number', models.CharField(max_length=50, null=True, verbose_name='رقم البيت')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('payment_method', models.CharField(choices=[('PayPal', 'PayPal'), ('Credit Card', 'Credit Card'), ('Cash On Delivery', 'Cash On Delivery')], max_length=20, verbose_name='طريقة الدفع')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('stock_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
            ],
        ),
    ]
