# Generated by Django 5.0.3 on 2024-04-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='stock_id',
            field=models.PositiveIntegerField(),
        ),
    ]
