# Generated by Django 5.0.3 on 2024-03-27 14:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='الصورة')),
                ('url', models.URLField(blank=True, null=True, verbose_name='رابط  يفتح عند الضغط على الصورة')),
                ('location', models.CharField(choices=[('main_banner_dynamic', 'أعلى الصفحة (متحرك)'), ('main_banner_static', 'أعلى الصفحة (ثابت)'), ('top_selling_banner', 'فوق الأعلى مبيعاً'), ('recently_arrived_banner', 'فوق وصل حديثاً'), ('customer_review', 'آراء العملاء')], max_length=50, verbose_name='موقعها فى الصفحة الرئيسية')),
            ],
            options={
                'verbose_name': 'الرآية',
                'verbose_name_plural': 'الرآيات',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'الفئة',
                'verbose_name_plural': 'الفئات',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'اللون',
                'verbose_name_plural': 'الألوان',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'المقاس',
                'verbose_name_plural': 'المقاسات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='الاسم')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('feature', models.CharField(choices=[('top_discounts', 'أقوى التخفيضات'), ('top_selling', 'المنتجات الأكثر مبيعاً'), ('recently_arrived', 'وصل حديثاً'), ('None', 'لا يوجد')], db_index=True, default='None', max_length=20, verbose_name='الميزة')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='السعر')),
                ('reviews_count', models.PositiveBigIntegerField(default=0, verbose_name='عدد المراجعات')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='الخصم بالجنية')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='تقييم المنتج')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'المنتج',
                'verbose_name_plural': 'المنتجات',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='الصورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صورة المنتج',
                'verbose_name_plural': 'صور المنتجات',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية')),
                ('color', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.color', verbose_name='اللون')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='inventory.product', verbose_name='مخزون')),
                ('size', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.size', verbose_name='المقاس')),
            ],
            options={
                'verbose_name': 'المخزون',
                'verbose_name_plural': 'مخزون المنتجات',
            },
        ),
    ]
