# Generated by Django 5.0.3 on 2024-04-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='products/', verbose_name='الصورة الرئيسية للمنتج'),
        ),
    ]
