# Generated by Django 5.0.3 on 2024-03-27 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(unique=True, upload_to='products/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.product', verbose_name='مخزون'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('color', 'size', 'product')},
        ),
    ]
