# Generated by Django 5.0.1 on 2024-03-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='number of reviews'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.CharField(choices=[('top_discounts', 'top discounts'), ('top_selling', 'top selling'), ('recently_arrived', 'recently arrived'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
