# Generated by Django 5.0.3 on 2024-03-22 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_product_reviews_count_alter_product_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='landing_page.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='number of reviews'),
        ),
    ]
