# Generated by Django 5.0.3 on 2024-03-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_alter_product_category_alter_product_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='main_image',
            field=models.ImageField(default='', upload_to='', verbose_name='main image'),
            preserve_default=False,
        ),
    ]
