# Generated by Django 5.0.3 on 2024-03-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_image_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='main_image',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='', upload_to='', verbose_name='main image'),
            preserve_default=False,
        ),
    ]
