# Generated by Django 5.0.3 on 2024-03-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_alter_image_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='Size',
            new_name='Size_id',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='product',
            new_name='product_id',
        ),
    ]
