# Generated by Django 5.0.3 on 2024-03-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0007_rename_product_image_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='Size_id',
            new_name='Size',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='product_id',
            new_name='product',
        ),
    ]
