# Generated by Django 5.0.3 on 2024-03-22 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0008_rename_product_id_image_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='url',
        ),
        migrations.AddField(
            model_name='banner',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing_page.product'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
