# Generated by Django 5.0.3 on 2024-03-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0009_remove_banner_url_banner_product_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='products/', verbose_name='main image'),
        ),
    ]
