# Generated by Django 5.0.3 on 2024-03-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0010_alter_image_id_alter_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
