# Generated by Django 5.0.3 on 2024-03-22 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0012_remove_product_main_image_alter_image_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='product',
        ),
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
