# Generated by Django 5.0.3 on 2024-03-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0013_remove_banner_product_banner_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
